version: 1.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\open-samp-api

platform: Win32
configuration: Release

install:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - nuget restore src\Open-SAMP-API.sln
    - MSBuild src\Open-SAMP-API.sln /p:Configuration=Release /p:Platform=Win32

    
    
