version: 1.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\open-samp-api

platform: Win32
configuration: Release

before_build:
    cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    
build:
    project: src\Open-SAMP-API.sln
    
