version: 2.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\open-samp-api

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

platform: Win32
configuration: Release

install:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - nuget restore src\Open-SAMP-API.sln

build_script:
    - cmd: MSBuild src\Open-SAMP-API.sln /p:Configuration=Release /p:Platform=Win32

after_build:
    - 7z a API.zip bin include test examples
    
artifacts:
    path: API.zip
    name: API

  
deploy:
    provider: GitHub
    auth_token:
        secure: G3Sfnp3bZeRUQNfYjuJB+8zbF5DXhMfj0wRad5ALRIZiGZodgrpOSj/umuR0zsGt
    artifact: API.zip
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true
