version: 1.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\open-samp-api

platform: Win32
configuration: Release

install:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - nuget restore src\Open-SAMP-API.sln

build_script:
    - cmd: MSBuild src\Open-SAMP-API.sln /p:Configuration=Release /p:Platform=Win32

after_build:
    - 7z a API.zip bin include test
    
artifacts:
    path: API.zip
    name: API

deploy:
- provider: GitHub
  release: API $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: G3Sfnp3bZeRUQNfYjuJB+8zbF5DXhMfj0wRad5ALRIZiGZodgrpOSj/umuR0zsGt
  artifact: API.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
  
